
#define NEURONDATAREADER_PROJECT_NAME        "NeuronDataReader"
#define NEURONDATAREADER_PROJECT_DESCRIPTION "Everything realted to NeuronDataReader"

#define NEURONDATAREADER_AUTHOR_ORGANIZATION "NeuronDataReader 1.0"
#define NEURONDATAREADER_AUTHOR_DOMAIN       "http://www.noitom.com"
#define NEURONDATAREADER_AUTHOR_MAINTAINER   "contact@noitom.com"

#define NEURONDATAREADER_VERSION_MAJOR       "1"
#define NEURONDATAREADER_VERSION_MINOR       "1"
#define NEURONDATAREADER_VERSION_PATCH       "3"
#define NEURONDATAREADER_VERSION_REVISION    "470"

#define NEURONDATAREADER_VERSION             "1.1.3"
#define NEURONDATAREADER_NAME_VERSION        "NeuronDataReader v1.1.3 (470)"
